- name: Setup Terraform Environment
  hosts: localhost
  become: yes
  tasks:

    - name: Install dependencies (KVM, Libvirt, Terraform)
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Add HashiCorp GPG key
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      args:
        creates: /etc/apt/sources.list.d/hashicorp.list

    - name: Install Terraform
      apt:
        name: terraform
        state: present
        update_cache: yes

    - name: Add user to libvirt and KVM groups
      user:
        name: "{{ ansible_user_id }}"
        groups: libvirt,kvm
        append: yes

    - name: Start and enable Libvirt
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Download Ubuntu cloud image
      get_url:
        url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        dest: /var/lib/libvirt/images/ubuntu.qcow2
        mode: '0644'

    - name: Ensure Terraform directory exists
      file:
        path: /home/{{ ansible_user_id }}/terraform-vm
        state: directory
        mode: '0755'

    - name: Define default Libvirt storage pool
      command: virsh pool-define-as --name default --type dir --target /var/lib/libvirt/images
      ignore_errors: yes

    - name: Start default Libvirt storage pool
      command: virsh pool-start default
      ignore_errors: yes

    - name: Enable default Libvirt storage pool to start on boot
      command: virsh pool-autostart default
      ignore_errors: yes
