- name: Setup Terraform Environment
  hosts: localhost
  become: true
  tasks:

    - name: Install dependencies (KVM, Libvirt, Terraform, Curl)
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
          - software-properties-common
          - gnupg
          - curl  # Added curl installation
        state: present
        update_cache: yes

    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present

    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: hashicorp
        state: present
        update_cache: yes

    - name: Check if Homebrew is already installed
      command: which brew
      register: homebrew_installed
      ignore_errors: yes
      changed_when: false

    - name: Install Homebrew (if not installed)
      become: false  # Run as normal user (Fixes "Don't run this as root!" issue)
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        executable: /bin/bash
      when: homebrew_installed.rc != 0

    - name: Install Terraform via Homebrew
      become: false  # Run as normal user
      community.general.homebrew:
        name: terraform
        state: present
        path: /home/linuxbrew/.linuxbrew/bin

    - name: Add user to libvirt and KVM groups
      user:
        name: "{{ ansible_user_id }}"
        groups: libvirt,kvm
        append: yes

    - name: Start and enable Libvirt
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Download AlmaLinux cloud image
      get_url:
        url: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
        dest: /var/lib/libvirt/images/almalinux.qcow2
        mode: '0644'

    - name: Ensure Terraform directory exists
      file:
        path: /home/{{ ansible_user_id }}/terraform-vm
        state: directory
        mode: '0755'

    - name: Define default Libvirt storage pool
      command: virsh pool-define-as --name default --type dir --target /var/lib/libvirt/images
      ignore_errors: yes

    - name: Start default Libvirt storage pool
      command: virsh pool-start default
      ignore_errors: yes

    - name: Enable default Libvirt storage pool to start on boot
      command: virsh pool-autostart default
      ignore_errors: yes

