---
- name: Verify Centralized Logging Configuration
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if rsyslog is installed
      command: which rsyslogd
      register: rsyslog_installed
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ rsyslog Installed: {{ 'PASS' if rsyslog_installed.rc == 0 else 'FAIL' }}"

    - name: Check if rsyslog server is listening on port 514
      shell: "ss -tuln | grep ':514 '"
      register: rsyslog_port
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Syslog Server Listening: {{ 'PASS' if rsyslog_port.stdout else 'FAIL' }}"

    - name: Check if rsyslog client is forwarding logs
      shell: "grep '@' /etc/rsyslog.conf"
      register: rsyslog_client
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Syslog Client Forwarding Logs: {{ 'PASS' if rsyslog_client.stdout else 'FAIL' }}"

    - name: Check if logs are being received on syslog server
      shell: "journalctl -u rsyslog | grep -i 'client'"
      register: rsyslog_received
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Logs Received on Syslog Server: {{ 'PASS' if rsyslog_received.stdout else 'FAIL' }}"

