---
- name: Verify RAID 5 Configuration
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if mdadm is installed
      command: which mdadm
      register: mdadm_installed
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ mdadm Installed: {{ 'PASS' if mdadm_installed.rc == 0 else 'FAIL' }}"

    - name: Check if RAID 5 array is detected
      shell: "cat /proc/mdstat | grep -i 'raid5'"
      register: raid_status
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ RAID 5 Array Detected: {{ 'PASS' if raid_status.stdout else 'FAIL' }}"

    - name: Check if RAID array is formatted
      shell: "blkid | grep '/dev/md0'"
      register: raid_format
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ RAID Array Formatted: {{ 'PASS' if raid_format.stdout else 'FAIL' }}"

    - name: Check if RAID array is mounted persistently at /data
      shell: "grep '/dev/md0' /etc/fstab"
      register: raid_fstab
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ RAID Array Mounted Persistently: {{ 'PASS' if raid_fstab.stdout else 'FAIL' }}"

