---
- name: Verify Custom Kernel Deployment
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if kernel source exists
      stat:
        path: /usr/src/linux  # Change if the path is different
      register: kernel_source
    - debug:
        msg: "✅ Kernel Source Exists: {{ 'PASS' if kernel_source.stat.exists else 'FAIL' }}"

    - name: Check if necessary build tools are installed
      shell: "which gcc make bc bison flex"
      register: build_tools
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Build Tools Installed: {{ 'PASS' if build_tools.rc == 0 else 'FAIL' }}"

    - name: Check if kernel compilation was successful
      stat:
        path: /usr/src/linux/arch/x86/boot/bzImage  # Adjust based on architecture
      register: kernel_compiled
    - debug:
        msg: "✅ Kernel Compilation Successful: {{ 'PASS' if kernel_compiled.stat.exists else 'FAIL' }}"

    - name: Check if custom kernel is installed in grub
      shell: "grep 'menuentry ' /boot/grub2/grub.cfg | grep -i custom"
      register: grub_entry
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Custom Kernel Installed in GRUB: {{ 'PASS' if grub_entry.stdout else 'FAIL' }}"

    - name: Check if system is running the custom kernel
      shell: "uname -r"
      register: running_kernel
      changed_when: false
    - debug:
        msg: "✅ Running Custom Kernel: {{ 'PASS' if 'custom' in running_kernel.stdout else 'FAIL' }}"

