---
- name: Verify Nginx Custom Configuration
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if Nginx is installed
      command: nginx -v
      register: nginx_installed
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Nginx Install: {{ 'PASS' if nginx_installed.rc == 0 else 'FAIL' }}"

    - name: Check if Nginx service is running
      systemd:
        name: nginx
        state: started
      register: nginx_status
      ignore_errors: yes
    - debug:
        msg: "✅ Nginx Running: {{ 'PASS' if nginx_status.status.ActiveState == 'active' else 'FAIL' }}"

    - name: Check if Nginx is listening on port 8080
      shell: "ss -tln | grep ':8080'"
      register: nginx_port
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Nginx Port: {{ 'PASS' if nginx_port.rc == 0 else 'FAIL' }}"

    - name: Verify SSL Certificate Exists
      stat:
        path: /etc/nginx/ssl/nginx.crt
      register: ssl_cert
    - debug:
        msg: "✅ SSL Certificate: {{ 'PASS' if ssl_cert.stat.exists else 'FAIL' }}"

    - name: Verify SSL Key Exists
      stat:
        path: /etc/nginx/ssl/nginx.key
      register: ssl_key
    - debug:
        msg: "✅ SSL Key: {{ 'PASS' if ssl_key.stat.exists else 'FAIL' }}"

