---
- name: Verify Network Configuration
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if default gateway is set
      shell: "ip route show | grep default"
      register: default_gateway
      changed_when: false
    - debug:
        msg: "✅ Default Gateway Configured: {{ 'PASS' if default_gateway.stdout else 'FAIL' }}"

    - name: Test network connectivity
      shell: "ping -c 1 8.8.8.8"
      register: network_ping
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Network Connectivity Works: {{ 'PASS' if network_ping.rc == 0 else 'FAIL' }}"

    - name: Test DNS resolution
      shell: "ping -c 1 google.com"
      register: dns_test
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ DNS Resolution Works: {{ 'PASS' if dns_test.rc == 0 else 'FAIL' }}"

