---
- name: Verify Package Manager Integrity
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if dnf or yum is installed
      command: which dnf || which yum
      register: package_manager
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Package Manager Installed: {{ 'PASS' if package_manager.rc == 0 else 'FAIL' }}"

    - name: Check if GPG keys are present
      shell: "ls /etc/pki/rpm-gpg/"
      register: gpg_keys
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ GPG Keys Present: {{ 'PASS' if gpg_keys.stdout else 'FAIL' }}"

    - name: Test if package manager can update
      command: dnf check-update
      register: package_update
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Package Manager Can Update: {{ 'PASS' if package_update.rc == 0 else 'FAIL' }}"

