---
- name: Verify Resource Exhaustion Attack
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if cron service is running
      shell: "systemctl is-active crond"
      register: cron_service
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Cron Service Running: {{ 'PASS' if cron_service.stdout == 'active' else 'FAIL' }}"

    - name: Check for high CPU usage
      shell: "ps -eo pid,%cpu,cmd --sort=-%cpu | head -n 5"
      register: high_cpu_process
      changed_when: false
    - debug:
        msg: "✅ High CPU Usage Detected: {{ 'PASS' if high_cpu_process.stdout else 'FAIL' }}"

    - name: Check if system is responsive
      shell: "uptime"
      register: system_responsive
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ System Still Responsive: {{ 'PASS' if system_responsive.stdout else 'FAIL' }}"

    - name: Check if faulty cron job exists
      shell: "crontab -l 2>/dev/null | grep -i 'while :; do :; done'"
      register: faulty_cron
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Faulty Cron Job Detected: {{ 'PASS' if faulty_cron.stdout else 'FAIL' }}"

