---
- name: Verify Boot Loader Integrity (Wildcard-based GRUB search)
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Ensure debsums is installed
      apt:
        name: debsums
        state: present

    - name: Run debsums to find corrupt files
      shell: "debsums -c"
      register: debsums_output
      changed_when: false
      failed_when: false

    - name: Show debsums results
      debug:
        msg: "{{ debsums_output.stdout | default('No output') }}"
