---
- name: Verify Cron Job Integrity
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if cron service is running
      shell: "systemctl is-active crond"
      register: cron_service
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Cron Service Running: {{ 'PASS' if cron_service.stdout == 'active' else 'FAIL' }}"

    - name: Check if crontab contains valid jobs
      shell: "crontab -l 2>/dev/null | grep -v '^#' | grep -v '^$'"
      register: cron_jobs
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Valid Cron Jobs Found: {{ 'PASS' if cron_jobs.stdout else 'FAIL' }}"

    - name: Check if cron logs contain errors
      shell: "journalctl -u crond | grep -i 'error'"
      register: cron_errors
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ No Cron Errors: {{ 'PASS' if not cron_errors.stdout else 'FAIL' }}"

