---
- name: Sabotage GRUB for Testing
  hosts: localhost
  become: true
  gather_facts: no

  tasks:
    - name: Remove /etc/default/grub to fail "GRUB Config Exists" check
      file:
        path: /etc/default/grub
        state: absent
      ignore_errors: yes

    - name: Remove /boot/grub2/grub.cfg to fail "GRUB Bootloader Exists" check
      file:
        path: /boot/grub2/grub.cfg
        state: absent
      ignore_errors: yes

    - name: OR remove 'root=' lines from grub.cfg to fail "GRUB Root Partition Configured"
      # Uncomment if you prefer removing the root line instead of the entire file:
      # lineinfile:
      #   path: /boot/grub2/grub.cfg
      #   regexp: 'root='
      #   state: absent
      # ignore_errors: yes

    - name: Force a kernel error in the logs to fail "No Kernel Boot Errors" check
      shell: "logger -p err 'Simulated kernel error: This is a test error for demonstration'"
      ignore_errors: yes

    - name: Stop the system for "System Boot Status" check (extreme sabotage!)
      shell: "systemctl poweroff"
      # If you only want to degrade state but keep the host up, you could do:
      # shell: "systemctl emergency"
      ignore_errors: yes
