---
- name: Sabotage GRUB for Testing (Version-Independent)
  hosts: localhost
  become: true
  gather_facts: no

  vars:
    possible_grub_dirs:
      - "/boot/grub2"
      - "/boot/grub"

  tasks:
    - name: Find existing grub.cfg path
      stat:
        path: "{{ item }}/grub.cfg"
      register: grub_files
      loop: "{{ possible_grub_dirs }}"

    - name: Set sabotage_grub_cfg if found
      set_fact:
        sabotage_grub_cfg: "{{ item.item }}/grub.cfg"
      when: item.stat.exists
      loop: "{{ grub_files.results }}"

    - name: Debug the discovered GRUB config path
      debug:
        msg: "Will sabotage grub.cfg at: {{ sabotage_grub_cfg | default('No GRUB config found!') }}"

    - name: Remove /etc/default/grub to fail GRUB Config check
      file:
        path: /etc/default/grub
        state: absent
      ignore_errors: yes

    - name: Remove 'root=' lines from grub.cfg to fail 'GRUB Root Partition Configured' check
      lineinfile:
        path: "{{ sabotage_grub_cfg | default('/boot/grub2/grub.cfg') }}"
        regexp: 'root='
        state: absent
      ignore_errors: yes

    - name: Force a kernel error in the logs to fail 'No Kernel Boot Errors' check
      shell: "logger -p err 'Simulated kernel error: This is a test error for demonstration'"
      ignore_errors: yes
