---
- name: Verify Filesystem Integrity
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if filesystem is mounted
      shell: "mount | grep ext4"
      register: fs_mounted
      changed_when: false
    - debug:
        msg: "✅ Filesystem Mounted: {{ 'PASS' if fs_mounted.stdout else 'FAIL' }}"

    - name: Check filesystem integrity with fsck
      shell: "fsck -n /dev/sdX"  # Replace /dev/sdX with actual partition
      register: fsck_output
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Filesystem Integrity Check: {{ 'PASS' if 'clean' in fsck_output.stdout else 'FAIL' }}"

    - name: Check dmesg logs for filesystem errors
      shell: "dmesg | grep -i 'EXT4-fs error'"
      register: fs_errors
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ No Filesystem Errors in Logs: {{ 'PASS' if not fs_errors.stdout else 'FAIL' }}"

