---
- name: Add host and vars
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
    - name: Ensure TESTENV_ADDRESS is set
      ansible.builtin.assert:
        that: lookup('env','TESTENV_ADDRESS') | length > 0

    - name: Add TESTENV_ADDRESS to 'testenv' and pass payload
      ansible.builtin.add_host:
        name: "{{ lookup('env','TESTENV_ADDRESS') }}"
        groups: testenv
        my_payload:
          user: "{{ lookup('env','SSH_USER') | default('ubuntu', true) }}"
          note: "from runner"

- name: Run all check task files
  hosts: testenv
  gather_facts: no
  tasks:
    - name: Include all task files in checks/
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ lookup('fileglob', 'checks/*.yml', wantlist=True) }}"

