Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"  # AlmaLinux 9 image
  config.vm.hostname = "almalinux-vm"
  config.vm.network "private_network", ip: "192.168.56.100"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl enable --now sshd
    sudo yum update -y
    sudo yum upgrade -y
    sudo yum install -y golang

  SHELL
end
