- name: Setup Terraform Environment
  hosts: localhost
  become: true
  tasks:
    - name: Ensure required Ansible collections are installed
      ansible.builtin.command: ansible-galaxy collection install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"  # Ensures it runs in the same directory as the playbook
      changed_when: false


    - name: Install dependencies (KVM, Libvirt, Terraform)
      ansible.builtin.package:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
          - software-properties-common
          - gnupg
        state: present
        update_cache: true
      when: ansible_pkg_mgr is defined

    - name: Install Homebrew if not installed
      ansible.builtin.shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew  # ✅ Ensures the command runs only if Homebrew is missing

    - name: Ensure Homebrew is in PATH
      ansible.builtin.lineinfile:
        path: /etc/profile.d/homebrew.sh
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        create: true
        mode: '0644'

    # ✅ Install Terraform via Homebrew
    - name: Install Terraform via Homebrew
      community.general.homebrew:
        name: terraform
        state: present

    - name: Add user to libvirt and KVM groups
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: libvirt,kvm
        append: true

    - name: Start and enable Libvirt
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Download AlmaLinux cloud image
      ansible.builtin.get_url:
        url: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
        dest: /var/lib/libvirt/images/almalinux.qcow2
        mode: '0644'

    - name: Ensure Terraform directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/terraform-vm"
        state: directory
        mode: '0755'

    - name: Ensure default Libvirt storage pool is defined, started, and enabled
      community.libvirt.virt_pool:
        name: default
        state: active   # This defines & starts the pool in one step
        autostart: true
        xml: |
          <pool type='dir'>
            <name>default</name>
            <target>
              <path>/var/lib/libvirt/images</path>
            </target>
          </pool>
