Vagrant.configure("2") do |config|
  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "almalinux/9"
    monitor.vm.hostname = "monitor"
    monitor.vm.network "private_network", ip: "192.168.56.10"
    monitor.vm.provision "file", source: "monitor_service.go", destination: "/home/vagrant/monitor_service.go"
  end

  config.vm.define "testenv" do |testenv|
    testenv.vm.box = "almalinux/9"
    testenv.vm.hostname = "testenv"
    testenv.vm.network "private_network", ip: "192.168.56.11"
    testenv.vm.provision "file", source: "test_environment.go", destination: "/home/vagrant/test_environment.go"
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    sudo systemctl enable --now sshd
#    sudo yum update -y
#    sudo yum upgrade -y
#    sudo yum install -y golang
#  SHELL
end
