---
- name: Ensure results dir exists
  ansible.builtin.file:
    path: "{{ _rad }}"
    state: directory
    mode: "0755"

- name: Verify files with rpm -Vf
  become: yes
  ansible.builtin.command: "rpm -Vf {{ f }}"
  loop: "{{ corruptedFile | default([]) }}"
  loop_control:
    loop_var: f
  register: verify
  changed_when: false
  failed_when: false

# NEW: make sure {{ _rad }} exists before we write into it
- name: Ensure results dir exists
  ansible.builtin.file:
    path: "{{ _rad }}"
    state: directory
    mode: "0755"

# REPLACE your old "Save raw output" with this one
- name: Save raw output
  ansible.builtin.copy:
    dest: "{{ _rad }}/rpm_verify.txt"
    content: |
      {% for r in (verify.results | default([])) %}
      PATH: {{ r.f | default(r.item, true) }}
      RC:   {{ r.rc | default('') }}
      OUT:  {{ (r.stdout | default('') | trim) }}
      ERR:  {{ (r.stderr | default('') | trim) }}
      ---
      {% endfor %}
    mode: "0644"

- name: Set check_result
  ansible.builtin.set_fact:
    check_result:
      id: "{{ _cid }}"
      status: "{{ 'fail' if (verify.results | selectattr('rc','ne',0) | list | length) > 0 else 'pass' }}"
      summary: "{{ (verify.results | selectattr('rc','ne',0) | list | length) }} file(s) failed rpm verification"
      data:
        failed_paths: "{{ verify.results | selectattr('rc','ne',0) | map(attribute='f') | list }}"
        checked_paths: "{{ verify.results | map(attribute='f') | list }}"

- name: Debug check_result
  ansible.builtin.debug:
    var: check_result
