---
- name: Verify files with rpm -Vf
  become: yes
  ansible.builtin.command: "rpm -Vf {{ f }}"
  loop: "{{ corruptedFile | default([]) }}"
  loop_control:
    loop_var: f
  register: verify
  changed_when: false
  failed_when: false

- name: Save raw output
  ansible.builtin.copy:
    dest: "{{ _rad }}/rpm_verify.txt"
    content: |
      {% for r in verify.results %}
      PATH: {{ r.f | default(r.item, true) }}
      RC:   {{ r.rc }}
      OUT:  {{ (r.stdout | trim) | default('') }}
      ERR:  {{ (r.stderr | trim) | default('') }}
      ---
      {% endfor %}
    mode: "0644"

- name: Set check_result
  ansible.builtin.set_fact:
    check_result:
      id: "{{ _cid }}"
      status: "{{ 'fail' if (verify.results | selectattr('rc','ne',0) | list | length) > 0 else 'pass' }}"
      summary: "{{ (verify.results | selectattr('rc','ne',0) | list | length) }} file(s) failed rpm verification"
      data:
        failed_paths: "{{ verify.results | selectattr('rc','ne',0) | map(attribute='f') | list }}"
        checked_paths: "{{ verify.results | map(attribute='f') | list }}"
