---
- name: Verify Memory Leak Diagnosis Setup
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Check if valgrind is installed
      command: which valgrind
      register: valgrind_installed
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ Valgrind Installed: {{ 'PASS' if valgrind_installed.rc == 0 else 'FAIL' }}"

    - name: Check if pmap is installed
      command: which pmap
      register: pmap_installed
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ pmap Installed: {{ 'PASS' if pmap_installed.rc == 0 else 'FAIL' }}"

    - name: Check if memory-intensive processes are running
      shell: "ps aux --sort=-%mem | head -n 5"
      register: high_memory_process
      changed_when: false
    - debug:
        msg: "✅ High Memory Processes Detected: {{ 'PASS' if high_memory_process.stdout else 'FAIL' }}"

    - name: Check if Out of Memory (OOM) errors exist in dmesg
      shell: "dmesg | grep -i 'Out of memory'"
      register: oom_errors
      ignore_errors: yes
      changed_when: false
    - debug:
        msg: "✅ No OOM Errors: {{ 'PASS' if not oom_errors.stdout else 'FAIL' }}"

    - name: Check if available memory is above 500MB
      shell: "free -m | awk '/Mem:/ {print $7}'"
      register: free_mem
      changed_when: false
    - debug:
        msg: "✅ Available Memory Above 500MB: {{ 'PASS' if free_mem.stdout|int > 500 else 'FAIL' }}"

